--- #YAML:1.0
name:                chklinks
version:             3.09
abstract:            A non-threaded Perl link checker
license:             gpl
author:              
    - imacat <imacat@mail.imacat.idv.tw>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
    HTML::LinkExtor:               0
    HTTP::Cookies:                 0
    HTTP::Request:                 0
    LWP::RobotUA:                  0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
